Develop tk
Skyblueballykid/kiva-crowd pull request #15
Opened 2020-03-13 04:51 UTC by Skyblueballykid

I added a Dockerfile (I tried to follow Skylar's instructions) and updated docker-compose, let me know what you guys think.

2020-03-13 18:25 UTC, skyripley requested changes
Can you also add some info to the readme so that everyone knows how to run this locally with `docker-compose`? And let me know when you're finished with the changes so that I can re-review (or you can re-request a review)

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +    build: ./backend
```suggestion
    build: 
      context: ./backend
```

2020-03-13 18:25 UTC, skyripley commented on Dockerfile
> +FROM python:3
We need to move this file to the `backend` directory

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +  web:
```suggestion
  backend:
    container_name: backend
```

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +    - .:/var/app
```suggestion
    - ./backend:/var/app
```

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +        - postgres
I noticed that there's a race condition between postgres actually starting and django trying to connect to it. This `depends_on` will make the `web` (or `backend`) service wait for the `postgres` container to start, but it doesn't wait for postgres itself to start. This means that occasionally when we run `docker-compose up --build`, or whatever command you're using, django will fail to connect to the db. One workaround would be to start the services separately and make sure that postgres itself starts before starting the backend service. Seems like some people recommend using https://github.com/vishnubob/wait-for-it or adding a health check to the `postgres` service and forcing the `backend` service to wait for it to be healthy, but I'm curios if @ntt2k might already know of a good method since he's familiar with django

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +        - "8000:8000"
```suggestion
    ports:
        - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
```

2020-03-13 18:25 UTC, skyripley commented on docker-compose.yml
> +        - "8000:8000"
This will make it so that we try to connect to the `postgres` container rather than localhost. Connecting to localhost will fail since we have two separate containers. 

Another option would be to create a `.env.example` file in the base directory of the project that we copy to `.env` before running docker-compose, add `POSTGRES_HOST=postgres` to that file, and add `env_file: ./.env` here so that we pull our "secrets" from an ephemeral file. Then we'd need to add `.env` to our `.gitignore` so that no one accidentally commits production secrets, and also move all of our other secrets here to that file. I'm fine with just doing the suggestion above though for now and we can make our secrets management better in another PR if we think it's necessary since this is probably a nice-to-have for a grad school project.

2020-03-13 18:59 UTC, Skyblueballykid commented
Cool, thanks for all the feedback. I will review when I get a chance and make the suggested changes...I might have some follow up questions.

2020-03-14 20:06 UTC, Skyblueballykid commented on docker-compose.yml
> +    build: ./backend
Done in latest commit.

2020-03-14 20:06 UTC, Skyblueballykid commented on docker-compose.yml
> +  web:
Done in latest commit.

2020-03-14 20:06 UTC, Skyblueballykid commented on Dockerfile
> +FROM python:3
Done in latest commit.

2020-03-14 20:07 UTC, Skyblueballykid commented on docker-compose.yml
> +    - .:/var/app
Done in latest commit.

2020-03-14 20:07 UTC, Skyblueballykid commented on docker-compose.yml
> +        - postgres
Still open.

2020-03-14 20:07 UTC, Skyblueballykid commented on docker-compose.yml
> +        - "8000:8000"
Done in latest commit.

2020-03-14 20:10 UTC, Skyblueballykid commented
I updated the docker-compose file to reflect Skylar's comments and moved the Dockerfile to backend. Let me know what you guys think, the YAML validates, but hopefully I got the indentation of everything right.

2020-03-15 01:04 UTC, skyripley approved these changes

2020-03-17 19:16 UTC, merged